version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb'
        restart: on-failure
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
    
